
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en' | 'ca' | 'fr' | 'de' | 'it';
type Theme = 'light' | 'dark';

interface SettingsContextType {
  lang: Language;
  theme: Theme;
  setLang: (lang: Language) => void;
  toggleTheme: () => void;
  t: (key: string) => string;
}

// Forced reload to clear vite cache
const translations: Record<Language, Record<string, string>> = {
  es: {
    "nav.home": "Inicio",
    "nav.login": "Iniciar Sesión",
    "nav.register": "Unirse Ahora",
    "nav.admin": "Panel Admin",
    "nav.logout": "Salir",
    "nav.continue": "Continuar Formación",
    "nav.back_admin": "Volver a Panel Admin",
    "hero.tag": "PROGRAMA OFICIAL",
    "hero.title": "Únete al Ecosistema Redescomerciales.ai",
    "hero.subtitle": "Transforma colaboradores en una red de ventas activa.",
    "hero.btn": "Unirse Ahora",
    "login.title": "Bienvenido de nuevo",
    "login.subtitle": "Accede de tu panel de gestión y continúa tu formación en el ecosistema.",
    "login.email": "Correo Electrónico",
    "login.email_placeholder": "tu@email.com",
    "login.password": "Contraseña",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Entrar al Portal",
    "login.forgot": "¿Has olvidado tu contraseña?",
    "login.new": "¿Nuevo en Redescomerciales.ai?",
    "login.register_link": "Crear cuenta profesional",
    "login.back": "Volver al login",
    "register.title": "Crea tu cuenta",
    "register.subtitle": "Únete al ecosistema líder en gestión de ayudas públicas.",
    "register.name": "Nombre Completo",
    "register.name_placeholder": "Ej: Juan Pérez",
    "register.email": "Email",
    "register.email_placeholder": "ejemplo@correo.com",
    "register.phone": "Teléfono",
    "register.phone_placeholder": "600 000 000",
    "register.level": "Nivel deseado",
    "register.pass": "Contraseña",
    "register.pass_confirm": "Confirmar Contraseña",
    "register.pass_placeholder": "••••••••",
    "register.btn": "Crear cuenta profesional",
    "register.existing": "¿Ya tienes una cuenta?",
    "register.login_link": "Inicia sesión aquí",
    "register.email_sent_title": "¡Casi listo!",
    "register.email_sent_desc": "Hemos enviado un correo de confirmación a",
    "register.role.1": "1 - Prescriptor",
    "register.role.2": "2 - Colaborador",
    "register.role.3": "3 - Delegado comercial",
    "register.role.4": "4 - Franquicia MOCOTA",
    "portal.title": "Panel de Carrera",
    "portal.subtitle": "Sigue tu itinerario profesional.",
    "footer.rights": "Transforma colaboradores en una red de ventas activa. Todos los derechos reservados.",
    "ecosystem.title": "Nuestro Ecosistema",
    "ecosystem.subtitle": "Cuatro niveles de colaboración adaptados para tu perfil.",
    "role.1.title": "Prescriptor",
    "role.1.desc": "Recomenda empresas y genera ingresos pasivos.",
    "role.1.subtitle": "Ideal para profesionales senior con una buena red de contactos que quieren generar ingresos extra sin carga operativa.",
    "role.1.perfil_title": "PERFIL IDEAL",
    "role.1.perfil_desc": "Personas que quieran monetizar sus contactos y generar ingresos adicionales. Ideal para consultores y profesionales de cualquier sector con una red activa de contactos.",
    "role.1.economico_title": "MODELO ECONÓMICO",
    "role.1.economico_desc": "Sin coste de entrada (0€). Por cada contacto que refieras y formalice un convenio, recibirás el 50% de su primera suscripción, lo que supone entre 100€ y 300€ por referido.",
    "role.1.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.1.f1": "Identificar contactos.",
    "role.1.f2": "Presentar la oportunidad.",
    "role.1.f3": "Nuestro equipo cierra la venta.",
    "role.1.ejemplo_title": "Ejemplo Real",
    "role.1.ejemplo_desc": "\"Caso Jorge (55 años): Consultor que monetiza su antigua agenda refiriendo empresas a Redescomerciales.ai sin involucrarse en la gestión.\"",
    "role.2.title": "Colaborador",
    "role.2.desc": "Gestiona la relación inicial y cualifica leads.",
    "role.2.subtitle": "Perfecto para comerciales multicartera o agencias que buscan diversificar su oferta y aportar valor añadido a sus clientes.",
    "role.2.perfil_title": "PERFIL IDEAL",
    "role.2.perfil_desc": "Asesor comercial, Agencia de Marketing, Gestor.",
    "role.2.economico_title": "MODELO ECONÓMICO",
    "role.2.economico_desc": "Canon anual 3.000€. Comisionas un 15% recurrente.",
    "role.2.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.2.f1": "Discovery con el cliente.",
    "role.2.f2": "Demo de la plataforma.",
    "role.2.f3": "Gestión comercial (no técnica).",
    "role.2.ejemplo_title": "Ejemplo Real",
    "role.2.ejemplo_desc": "\"Caso Laura (38 años): Asesora comercial que complementa su portafolio actual vendiendo financiación pública a sus clientes Pymes.\"",
    "role.3.title": "Delegado comercial",
    "role.3.sub": "(GESTIÓN)",
    "role.3.desc": "Lidera territorios y crea tu propia red.",
    "role.3.subtitle": "Modelo para líderes con capacidad de gestión y visión comercial estratégica.",
    "role.3.perfil_title": "PERFIL IDEAL",
    "role.3.perfil_desc": "Emprendedor, Ex-directivo de banca, Líder de equipos.",
    "role.3.economico_title": "MODELO ECONÓMICO",
    "role.3.economico_desc": "Canon anual 12.000€. Comisionas un 30% + Rappels por volumen.",
    "role.3.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.3.f1": "Gestión de zona.",
    "role.3.f2": "Captación de prescriptores.",
    "role.3.f3": "Liderazgo comercial.",
    "role.3.ejemplo_title": "Ejemplo Real",
    "role.3.ejemplo_desc": "\"Caso Marcos (42 años): Vendedor de alto rendimiento que destaca por su capacidad comercial y gestión de equipos locales.\"",
    "role.4.title": "Franquicia MOCOTA",
    "role.4.sub": "(OFICINA TÉCNICA)",
    "role.4.desc": "Gestión integral 360º y relación institucional.",
    "role.4.subtitle": "El nivel más alto para consultoras establecidas que quieren gestionar el ciclo completo, desde la venta hasta la justificación.",
    "role.4.perfil_title": "PERFIL IDEAL",
    "role.4.perfil_desc": "Consultora de innovación, Despacho técnico, Gestoría grande.",
    "role.4.economico_title": "MODELO ECONÓMICO",
    "role.4.economico_desc": "Modelo de alto rendimiento. Potencial >480k€/año.",
    "role.4.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.4.f1": "Ciclo completo de venta.",
    "role.4.f2": "Redacción técnica con IA.",
    "role.4.f3": "Interlocución con organismos.",
    "role.4.ejemplo_title": "Ejemplo Real",
    "role.4.ejemplo_desc": "\"Caso Ana (40 años): Gestora que lidera una oficina técnica regional, controlando todo el proceso de subvenciones para sus clientes.\"",
    "portal.btn.info": "Saber más",
    "portal.btn.register_now": "Regístrate ahora",
    "matcher.title": "¿Tienes dudas de cuál encaja mejor con tu situación?",
    "matcher.desc": "Cuéntale a nuestro asistente tu perfil, disponibilidad y objetivos, y te recomendaremos el camino ideal.",
    "matcher.btn": "Consultar IA Matcher",
    "matcher.modal.title": "Asistente de Orientación",
    "matcher.modal.instruction": "Describe brevemente tu situación actual:",
    "matcher.modal.placeholder": "Ej: Soy comercial multicartera con 15 años de experiencia, tengo una cartera de clientes industriales y busco diversificar mis ingresos dedicando unas 10h semanales...",
    "matcher.modal.loading": "Analizando tu perfil...",
    "matcher.modal.btn": "Encontrar mi Rol Ideal",
    "matcher.modal.retry": "Probar de nuevo",
    "portal.status.locked": "Bloqueado",
    "portal.status.done": "Completado",
    "portal.status.ready": "Listo",
    "portal.btn.start": "Empezar",
    "portal.btn.review": "Repasar",
    "portal.module.1": "Módulo 1: Introducción",
    "portal.module.2": "Módulo 2: Cliente Ideal",
    "portal.module.3": "Módulo 3: Explicación",
    "portal.module.4": "Módulo 4: Proceso",
    "admin.nav.dashboard": "Resumen",
    "admin.nav.candidates": "Candidatos",
    "admin.nav.interviews": "Agenda",
    "admin.nav.settings": "Ajustes",
    "admin.stats.total": "CANDIDATOS",
    "admin.stats.interviews": "CITAS AGENDADES",
    "admin.stats.pending": "EN FORMACIÓN",
    "admin.stats.approved": "SELECCIONADOS",
    "admin.overview.recent": "Últimos Registros",
    "admin.status.review_cv": "Revisar CV",
    "admin.btn.manage": "Gestionar",
    "admin.btn.schedule_new": "Agendar Entrevista",
    "admin.modal.meet_title": "Enlace Sincronizado",
    "admin.modal.meet_join": "Unirse a la Llamada",
    "admin.modal.copied": "¡Copiado!",
    "admin.settings.tech_params": "Vincular Google Workspace",
    "admin.settings.tech_desc": "Conecta la cuenta contact@fundswin.ai para agendar por Google Meet.",
    "admin.settings.google_btn": "Vincular con Google",
    "admin.settings.google_done": "Cuenta Vinculada ✓",
    "admin.settings.sim_guests": "Módulos Formativos",
    "admin.roles.prescriptor": "Prescriptor",
    "admin.roles.colaborador": "Colaborador",
    "admin.roles.delegado_g": "Delegado comercial",
    "admin.roles.oficina_t": "Franquicia MOCOTA",
    "admin.status.training": "En formación",
    "admin.modal.schedule_title": "Agendar Cita",
    "admin.modal.choose": "Seleccionar...",
    "admin.modal.date": "Día",
    "admin.modal.time": "Hora",
    "admin.modal.save": "Confirmar Cita",
    "admin.modal.saving": "Agendando...",
    "admin.modal.cancel": "Cerrar",
    "admin.search.placeholder": "Buscar candidato..."
  },
  en: {
    "nav.home": "Home",
    "nav.login": "Login",
    "nav.register": "Join Now",
    "nav.admin": "Admin Panel",
    "nav.logout": "Logout",
    "nav.continue": "Continue Training",
    "nav.back_admin": "Back to Admin Panel",
    "hero.tag": "OFFICIAL PROGRAM",
    "hero.title": "Join the Redescomerciales.ai Ecosystem",
    "hero.subtitle": "Transform collaborators into an active sales network.",
    "hero.btn": "Join Now",
    "login.title": "Welcome back",
    "login.subtitle": "Access your management panel and continue your training.",
    "login.email": "Email Address",
    "login.email_placeholder": "you@email.com",
    "login.password": "Password",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Enter Portal",
    "login.forgot": "Forgot your password?",
    "login.new": "New to Redescomerciales.ai?",
    "login.register_link": "Create professional account",
    "login.back": "Back to login",
    "register.title": "Create your account",
    "register.subtitle": "Join the leading ecosystem in public aid management.",
    "register.name": "Full Name",
    "register.name_placeholder": "E.g.: John Doe",
    "register.email": "Email",
    "register.email_placeholder": "example@email.com",
    "register.phone": "Phone",
    "register.phone_placeholder": "600 000 000",
    "register.level": "Desired Level",
    "register.pass": "Password",
    "register.pass_confirm": "Confirm Password",
    "register.pass_placeholder": "••••••••",
    "register.btn": "Create professional account",
    "register.existing": "Already have an account?",
    "register.login_link": "Log in here",
    "register.email_sent_title": "Almost ready!",
    "register.email_sent_desc": "We have sent a confirmation email to",
    "register.role.1": "1 - Prescriber",
    "register.role.2": "2 - Collaborator",
    "register.role.3": "3 - Sales Delegate",
    "register.role.4": "4 - MOCOTA Franchise",
    "portal.title": "Career Portal",
    "portal.subtitle": "Follow your professional itinerary.",
    "footer.rights": "Transform collaborators into an active sales network. All rights reserved.",
    "ecosystem.title": "Our Ecosystem",
    "ecosystem.subtitle": "Four levels of collaboration adapted to your profile.",
    "role.1.title": "Prescriber",
    "role.1.desc": "Recommend companies and generate passive income.",
    "role.2.title": "Collaborator",
    "role.3.title": "Sales Delegate",
    "role.4.title": "MOCOTA Franchise",
    "portal.btn.info": "Learn More",
    "portal.btn.register_now": "Register Now",
    "matcher.title": "Have doubts about which fits best?",
    "matcher.desc": "Tell our assistant about your profile, availability and goals, and we will recommend the ideal path.",
    "matcher.btn": "Consult AI Matcher",
    "matcher.modal.title": "Orientation Assistant",
    "matcher.modal.instruction": "Briefly describe your current situation:",
    "matcher.modal.placeholder": "E.g.: I am a commercial with 15 years experience, I have a portfolio of industrial clients...",
    "matcher.modal.loading": "Analyzing...",
    "matcher.modal.btn": "Find My Ideal Role",
    "matcher.modal.retry": "Try again",
    "portal.status.locked": "Locked",
    "portal.status.done": "Done",
    "portal.status.ready": "Ready",
    "portal.btn.start": "Start",
    "portal.btn.review": "Review",
    "portal.module.1": "Module 1: Intro",
    "portal.module.2": "Module 2: Ideal Client",
    "portal.module.3": "Module 3: Explanation",
    "portal.module.4": "Module 4: Process",
    "admin.nav.dashboard": "Overview",
    "admin.nav.candidates": "Candidates",
    "admin.nav.interviews": "Schedule",
    "admin.nav.settings": "Settings",
    "admin.stats.total": "CANDIDATES",
    "admin.stats.interviews": "SCHEDULED APTS",
    "admin.stats.pending": "IN TRAINING",
    "admin.stats.approved": "SELECTED",
    "admin.overview.recent": "Recent Records",
    "admin.status.review_cv": "Review CV",
    "admin.btn.manage": "Manage",
    "admin.btn.schedule_new": "Schedule Interview",
    "admin.modal.meet_title": "Synchronized Link",
    "admin.modal.meet_join": "Join the Call",
    "admin.modal.copied": "Copied!",
    "admin.settings.tech_params": "Link Google Workspace",
    "admin.settings.tech_desc": "Connect contact@fundswin.ai account to schedule via Google Meet.",
    "admin.settings.google_btn": "Link with Google",
    "admin.settings.google_done": "Account Linked ✓",
    "admin.settings.sim_guests": "Training Modules",
    "admin.roles.prescriptor": "Prescriber",
    "admin.roles.colaborador": "Collaborator",
    "admin.roles.delegado_g": "Sales Delegate",
    "admin.roles.oficina_t": "MOCOTA Franchise",
    "admin.status.training": "In training",
    "admin.modal.schedule_title": "Schedule Appointment",
    "admin.modal.choose": "Select...",
    "admin.modal.date": "Day",
    "admin.modal.time": "Time",
    "admin.modal.save": "Confirm Appointment",
    "admin.modal.saving": "Scheduling...",
    "admin.modal.cancel": "Close",
    "admin.search.placeholder": "Search candidate..."
  },
  ca: {
    "nav.home": "Inici",
    "nav.login": "Iniciar Sessió",
    "nav.register": "Unir-se Ara",
    "nav.admin": "Panell Admin",
    "nav.logout": "Sortir",
    "nav.continue": "Continuar Formació",
    "nav.back_admin": "Tornar al Panell Admin",
    "hero.tag": "PROGRAMA OFICIAL",
    "hero.title": "Uneix-te a l'Ecosistema Redescomerciales.ai",
    "hero.subtitle": "Transforma col·laboradors en una xarxa de vendes activa.",
    "hero.btn": "Unir-se Ara",
    "register.title": "Crea el teu compte",
    "register.name_placeholder": "Ex: Joan Garcia",
    "register.email_placeholder": "exemple@correu.cat",
    "register.phone_placeholder": "600 000 000",
    "register.pass_confirm": "Confirmar Contrasenya",
    "register.pass_placeholder": "••••••••",
    "register.existing": "Ja tens un compte?",
    "register.login_link": "Inicia sessió aquí",
    "ecosystem.title": "El nostre Ecosistema",
    "ecosystem.subtitle": "Quatre nivells de col·laboració adaptats al teu perfil.",
    "role.1.title": "Prescriptor",
    "role.1.desc": "Recomana empreses i genera ingressos passius.",
    "role.2.title": "Col·laborador",
    "role.3.title": "Delegat comercial",
    "role.4.title": "Franquícia MOCOTA",
    "portal.btn.info": "Saber-ne més",
    "portal.btn.register_now": "Registra't ara",
    "matcher.title": "Tens dubtes de quin encaixa millor?",
    "matcher.desc": "Explica-li al nostre assistent el teu perfil, disponibilitat i objectius.",
    "matcher.btn": "Consultar IA Matcher",
    "matcher.modal.title": "Assistent d'Orientació",
    "admin.nav.dashboard": "Resum",
    "admin.nav.candidates": "Candidats",
    "admin.nav.interviews": "Agenda",
    "admin.nav.settings": "Ajustos",
    "admin.stats.total": "CANDIDATS",
    "admin.stats.interviews": "CITES AGENDADES",
    "admin.stats.pending": "EN FORMACIÓ",
    "admin.stats.approved": "SELECCIONATS",
    "admin.overview.recent": "Últims Registres",
    "admin.status.review_cv": "Revisar CV",
    "admin.btn.manage": "Gestionar",
    "admin.btn.schedule_new": "Agendar Entrevista",
    "admin.roles.prescriptor": "Prescriptor",
    "admin.roles.colaborador": "Colaborador",
    "admin.roles.delegado_g": "Delegat comercial",
    "admin.roles.oficina_t": "Franquícia MOCOTA",
    "admin.status.training": "En formació",
    "admin.modal.schedule_title": "Agendar Cita",
    "admin.modal.choose": "Seleccionar...",
    "admin.modal.date": "Data",
    "admin.modal.time": "Hora",
    "admin.modal.save": "Confirmar Cita",
    "admin.modal.saving": "Agendant...",
    "admin.modal.cancel": "Tancar",
    "admin.search.placeholder": "Cercar candidat...",
    "admin.settings.sim_guests": "Mòduls Formatius"
  },
  fr: {
    "nav.home": "Accueil",
    "nav.login": "Connexion",
    "nav.register": "S'inscrire",
    "nav.admin": "Panel Admin",
    "nav.logout": "Déconnexion",
    "nav.continue": "Continuer Formation",
    "nav.back_admin": "Retour au Panel Admin",
    "hero.tag": "PROGRAMME OFFICIEL",
    "hero.title": "Rejoignez l'écosystème Redescomerciales.ai",
    "register.name_placeholder": "Ex: Jean Dupont",
    "register.email_placeholder": "exemple@email.fr",
    "register.pass_confirm": "Confirmer mot de passe",
    "register.existing": "Déjà un compte?",
    "hero.subtitle": "Transformez vos collaborateurs en un réseau de vente actif.",
    "hero.btn": "S'inscrire",
    "ecosystem.title": "Notre Écosystème",
    "ecosystem.subtitle": "Quatre niveaux de collaboration adaptés à votre profil.",
    "role.1.title": "Prescripteur",
    "role.2.title": "Collaborateur",
    "role.3.title": "Délégué Commercial",
    "role.4.title": "Franchise MOCOTA",
    "portal.btn.info": "En savoir plus",
    "portal.btn.register_now": "S'inscrire maintenant",
    "matcher.title": "Des doutes sur le meilleur profil?",
    "matcher.desc": "Parlez de votre profil à notre assistant et il vous recommandera le chemin idéal.",
    "matcher.btn": "Consulter IA Matcher",
    "matcher.modal.title": "Assistant d'Orientation",
    "admin.nav.dashboard": "Résumé",
    "admin.nav.candidates": "Candidats",
    "admin.nav.interviews": "Agenda",
    "admin.nav.settings": "Réglages",
    "admin.stats.total": "CANDIDATS",
    "admin.stats.interviews": "RDV FIXÉS",
    "admin.stats.pending": "EN FORMATION",
    "admin.stats.approved": "SÉLECTIONNÉS",
    "admin.overview.recent": "Derniers Inscrits",
    "admin.btn.manage": "Gérer",
    "admin.btn.schedule_new": "Programmer RDV",
    "admin.status.training": "En formation",
    "admin.roles.prescriptor": "Prescripteur",
    "admin.roles.colaborador": "Collaborateur",
    "admin.roles.delegado_g": "Délégué Commercial",
    "admin.roles.oficina_t": "Franchise MOCOTA",
    "admin.settings.sim_guests": "Modules de Formation"
  },
  de: {
    "nav.home": "Startseite",
    "nav.login": "Anmelden",
    "nav.register": "Jetzt beitreten",
    "register.name_placeholder": "Z.B. Max Mustermann",
    "register.email_placeholder": "beispiel@email.de",
    "register.pass_confirm": "Passwort bestätigen",
    "register.existing": "Haben Sie bereits ein Konto?",
    "nav.admin": "Admin-Bereich",
    "nav.logout": "Abmelden",
    "nav.continue": "Schulung fortsetzen",
    "nav.back_admin": "Zurück zum Admin-Bereich",
    "hero.tag": "OFFIZIELLES PROGRAMM",
    "hero.title": "Werden Sie Teil des Redescomerciales.ai-Ökosystems",
    "hero.subtitle": "Verwandeln Sie Mitarbeiter en ein aktives Vertriebsnetz.",
    "hero.btn": "Jetzt beitreten",
    "ecosystem.title": "Unser Ökosystem",
    "ecosystem.subtitle": "Vier Kooperationsstufen, angepasst an Ihr Profil.",
    "role.1.title": "Empfehlungsgeber",
    "role.2.title": "Partner",
    "role.3.title": "Vertriebsdelegierter",
    "role.4.title": "MOCOTA Franchise",
    "portal.btn.info": "Mehr erfahren",
    "portal.btn.register_now": "Jetzt registrieren",
    "matcher.title": "Unsicher, welches Level passt?",
    "matcher.desc": "Erzählen Sie unserem KI-Assistenten von Ihrem Profil.",
    "matcher.btn": "KI Matcher konsultieren",
    "matcher.modal.title": "Orientierungs-Assistent",
    "admin.nav.dashboard": "Übersicht",
    "admin.nav.candidates": "Kandidaten",
    "admin.nav.interviews": "Termine",
    "admin.nav.settings": "Einstellungen",
    "admin.stats.total": "KANDIDATEN",
    "admin.stats.interviews": "GEPLANTE TERMINE",
    "admin.stats.pending": "IN SCHULUNG",
    "admin.stats.approved": "AUSGEWÄHLT",
    "admin.overview.recent": "Neueste Einträge",
    "admin.btn.manage": "Verwalten",
    "admin.btn.schedule_new": "Termin vereinbaren",
    "admin.status.training": "In Ausbildung",
    "admin.roles.prescriptor": "Empfehlungsgeber",
    "admin.roles.colaborador": "Partner",
    "admin.roles.delegado_g": "Vertriebsdelegierter",
    "admin.roles.oficina_t": "MOCOTA Franchise",
    "admin.settings.sim_guests": "Schulungsmodule"
  },
  it: {
    "nav.home": "Home",
    "nav.login": "Accedi",
    "nav.register": "Unisciti ora",
    "register.name_placeholder": "Es: Mario Rossi",
    "register.email_placeholder": "esempio@email.it",
    "register.pass_confirm": "Conferma password",
    "register.existing": "Hai già un account?",
    "nav.admin": "Pannello Admin",
    "nav.logout": "Esci",
    "nav.continue": "Continua Formazione",
    "nav.back_admin": "Torna al Pannello Admin",
    "hero.tag": "PROGRAMMA UFFICIALE",
    "hero.title": "Unisciti all'Ecosistema Redescomerciales.ai",
    "hero.subtitle": "Trasforma i collaboratori in una rete di vendita attiva.",
    "hero.btn": "Unisciti ora",
    "ecosystem.title": "Il nostro ecosistema",
    "ecosystem.subtitle": "Quattro livelli de collaborazione adatti al tuo profilo.",
    "role.1.title": "Segnalatore",
    "role.2.title": "Collaboratore",
    "role.3.title": "Delegato Commerciale",
    "role.4.title": "Franchigia MOCOTA",
    "portal.btn.info": "Scopri di más",
    "portal.btn.register_now": "Registrati ora",
    "matcher.title": "Dubbi su quale scegliere?",
    "matcher.desc": "Racconta al nostro assistente il tuo profilo e ti consiglieremo il cammino ideale.",
    "matcher.btn": "Consulta IA Matcher",
    "matcher.modal.title": "Assistente de Orientamento",
    "admin.nav.dashboard": "Sommario",
    "admin.nav.candidates": "Candidati",
    "admin.nav.interviews": "Agenda",
    "admin.nav.settings": "Impostazioni",
    "admin.stats.total": "CANDIDATI",
    "admin.stats.interviews": "APPUNTAMENTI",
    "admin.stats.pending": "IN FORMAZIONE",
    "admin.stats.approved": "SELEZIONATI",
    "admin.overview.recent": "Ultimi iscritti",
    "admin.btn.manage": "Gestisci",
    "admin.btn.schedule_new": "Pianifica Colloquio",
    "admin.status.training": "In formación",
    "admin.roles.prescriptor": "Segnalatore",
    "admin.roles.colaborador": "Collaboratore",
    "admin.roles.delegado_g": "Delegato Commerciale",
    "admin.roles.oficina_t": "Franchigia MOCOTA",
    "admin.settings.sim_guests": "Moduli Formativi"
  }
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider = ({ children }: { children?: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(() => (localStorage.getItem('gw_lang') as Language) || 'es');
  const [theme, setThemeState] = useState<Theme>(() => (localStorage.getItem('gw_theme') as Theme) || 'light');

  useEffect(() => {
    localStorage.setItem('gw_lang', lang);
  }, [lang]);

  useEffect(() => {
    localStorage.setItem('gw_theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  const toggleTheme = () => setThemeState(prev => prev === 'light' ? 'dark' : 'light');
  const setLang = (l: Language) => setLangState(l);
  
  const t = (key: string) => translations[lang][key] || translations['es'][key] || key;

  return (
    <SettingsContext.Provider value={{ lang, theme, setLang, toggleTheme, t }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) throw new Error('useSettings must be used within SettingsProvider');
  return context;
};
